[Unit]
After=syslog-ng@default.service
Requires=syslog-ng@default.service

[Service]
Environment="SOCKET=/run/mastodon-streaming/mastodon-streaming.sock"
Restart=always
RestartMaxDelaySec=10s
RestartSec=100ms
RestartSteps=5
RuntimeDirectory=mastodon-streaming
RuntimeDirectoryMode=750
StandardError=file:/run/syslog/mastodon-streaming
StandardOutput=file:/run/syslog/mastodon-streaming
