#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy nginx/nginx.conf

remote=root@grapheneos.social

rsync -rptcv --chmod=D755,F644 --delete --fsync --preallocate nginx/{nginx.conf,mime.types} $remote:/etc/nginx/
ssh $remote nginx -s reload

rsync -rptcv --chmod=D755,F644 --fsync --preallocate systemd/system/{mastodon-web,mastodon-streaming,redis}.service.d $remote:/etc/systemd/system/
rsync -ptcv --chmod=F644 --fsync --preallocate redis/redis.conf $remote:/etc/redis/redis.conf

rsync -ptcv --chmod=755 --fsync --preallocate remote-backup $remote:/usr/local/bin/
rsync -ptcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.timer $remote:/etc/systemd/system/remote-backup.timer
rsync -ptcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.service $remote:/etc/systemd/system/remote-backup.service
rsync -ptcv --chmod=644 --fsync --preallocate backup-public-key.txt cloud-archive-password.txt $remote:
