#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy nginx/nginx.conf

remote=root@grapheneos.social

rsync -rptcv --fsync --chmod=D755,F644 --delete nginx/{nginx.conf,mime.types} $remote:/etc/nginx/
rsync -ptcv --fsync --chmod=755 {local-backup,remote-backup} $remote:/usr/local/bin/
rsync -rptcv --fsync --chmod=D755,F644 systemd/system/{mastodon-web,mastodon-streaming,redis}.service.d $remote:/etc/systemd/system/
rsync -ptcv --fsync --chmod=F644 redis/redis.conf $remote:/etc/redis/redis.conf
rsync -ptcv --fsync --chmod=644 systemd/system/remote-backup.timer $remote:/etc/systemd/system/remote-backup.timer
rsync -ptcv --fsync --chmod=644 systemd/system/remote-backup.service $remote:/etc/systemd/system/remote-backup.service
ssh $remote nginx -s reload

echo
