#!/bin/bash

set -o errexit -o nounset -o pipefail

source venv/bin/activate

touch lock
exec {fd}< lock
if ! flock -n $fd; then
    echo already deploying >&2
    exit 1
fi

gixy --skips try_files_is_evil_too nginx/nginx.conf

remote=root@grapheneos.social

rsync -rpcv --chmod=D755,F644 --delete --fsync --preallocate nginx/{nginx.conf,mime.types} $remote:/etc/nginx/
ssh $remote nginx -s reload

rsync -rpcv --delete --chmod=D755,F644 --fsync --preallocate systemd/system/{mastodon-web,mastodon-streaming@,postgresql,valkey}.service.d $remote:/etc/systemd/system/
rsync -pcv --chmod=F644 --fsync --preallocate valkey/valkey.conf $remote:/etc/valkey/valkey.conf
ssh $remote usermod mastodon -G valkey
ssh $remote usermod http -G mastodon

rsync -pcv --chmod=755 --fsync --preallocate remote-backup $remote:/usr/local/bin/
rsync -pcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.timer $remote:/etc/systemd/system/remote-backup.timer
rsync -pcv --chmod=644 --fsync --preallocate systemd/system/remote-backup.service $remote:/etc/systemd/system/remote-backup.service
rsync -pcv --chmod=644 --fsync --preallocate backup-public-key.txt cloud-archive.sh $remote:
rsync -pcv --chmod=600 --chown postgres:postgres --fsync --preallocate postgres/data/{pg_hba,pg_ident,postgresql}.conf $remote:/var/lib/postgres/data/
