#!/bin/bash

set -o errexit -o nounset -o pipefail

remote=root@grapheneos.social

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
ssh $remote "rm -rf local-backup"
ssh $remote "mkdir local-backup"

ssh $remote "mkdir local-backup/$timestamp"
ssh $remote "pg_dumpall -U postgres > local-backup/$timestamp/all_databases.sql"
ssh $remote "cp /var/lib/valkey/dump.rdb local-backup/$timestamp/"
ssh $remote "mkdir -p local-backup/$timestamp/mastodon/public/system"
ssh $remote "cp -r /var/lib/mastodon/public/system/{accounts,media_attachments,site_uploads} local-backup/$timestamp/mastodon/public/system"
ssh $remote "cp /etc/mastodon.conf local-backup/$timestamp/"
ssh $remote "tar -cC local-backup $timestamp | zstd -9 --long | age -r \$(cat backup-public-key.txt) -o local-backup/$timestamp.tar.zst.age"
rsync -v --fsync --preallocate $remote:./local-backup/$timestamp.tar.zst.age backup/

ssh $remote "rm -rf local-backup"
