#!/bin/bash

set -o errexit -o nounset -o pipefail

remote=root@grapheneos.social

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)

ssh $remote "prepare-backup local-backup $timestamp"

rsync -v --fsync --preallocate $remote:./local-backup/$timestamp.tar.zst.age backup/

ssh $remote "rm -rf local-backup"
