#!/bin/bash

set -o errexit -o nounset -o pipefail

destination="$1"
timestamp="$2"

rm -rf "$destination"
mkdir "$destination"

mkdir "$destination/$timestamp"
pg_dumpall -U postgres > "$destination/$timestamp/all_databases.sql"
cp /var/lib/valkey/dump.rdb "$destination/$timestamp/"
mkdir -p "$destination/$timestamp/mastodon/public/system"
cp -r /var/lib/mastodon/public/system/{accounts,media_attachments,site_uploads} "$destination/$timestamp/mastodon/public/system"
cp /etc/mastodon.conf "$destination/$timestamp/"
tar -cC "$destination" "$timestamp" | zstd -9 --long | age -r $(cat backup-public-key.txt) -o "$destination/$timestamp.tar.zst.age"
