[Unit]
After=syslog-ng@default.service
Requires=syslog-ng@default.service

[Service]
Environment="SOCKET=/run/mastodon-web/mastodon-web.sock"
Environment="WEB_CONCURRENCY=6"
Restart=always
RestartMaxDelaySec=10s
RestartSec=100ms
RestartSteps=5
RuntimeDirectory=mastodon-web
RuntimeDirectoryMode=750
StandardOutput=file:/run/syslog/mastodon-web
StandardError=file:/run/syslog/mastodon-web
