name: Lint nginx configuration

on: [pull_request, push]

jobs:
  static:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip
    - run: 'pip install --require-hashes --only-binary :all: -r requirements.txt'
    - run: gixy --skips try_files_is_evil_too nginx/nginx.conf
